apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: gojobs-manager
    namespace: gojobs
rules:
    - apiGroups: ["", "extensions", "apps"]
      resources: ["pods", "jobs", "cronjobs"]
      verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: gojobs-manager-sa
    namespace: gojobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: manage-pods-jobs-cronjobs
    namespace: gojobs
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: gojobs-manager
subjects:
    - kind: ServiceAccount
      name: gojobs-manager-sa
      namespace: gojobs
